export const SET_SKIN ="SET_SKIN";
export const UPDATE_SKIN ="UPDATE_SKIN";
export const ADD_CONTACT="ADD_CONTACT";
export const ADD_EDUCATION="ADD_EDUCATION";

export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const REMOVE_ERROR = 'REMOVE_ERROR';


export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";

export const SIGN_UP_FAILED = "SIGN_IN_FAILED";
export const SIGN_UP_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_UP_REQUEST = "SIGN_REQUEST";

export const SIGN_OUT_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT_REQUEST = "SIGN_REQUEST";


export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

